In [1]:
import pandas as pd
pd.options.display.max_columns = 30

In [2]:
df = pd.read_csv('movies_metadata.csv',low_memory=False)

In [3]:
#check the dataframe
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [4]:
#check the information of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [5]:
df['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [6]:
df['belongs_to_collection'][0]

"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"

In [7]:
df.drop(columns= ['adult', 'imdb_id', 'original_title', 'video', 'homepage'], inplace = True)
# we do not need these columns , so we will drop them

In [8]:
#check information of df after drop
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4494 non-null   object
 1   budget                 45466 non-null  object
 2   genres                 45466 non-null  object
 3   id                     45466 non-null  object
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45461 non-null  object
 7   poster_path            45080 non-null  object
 8   production_companies   45463 non-null  object
 9   production_countries   45463 non-null  object
 10  release_date           45379 non-null  object
 11  revenue                45460 non-null  float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       45460 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: float64(4), object(15)
memory usage: 6.6+ MB

In [9]:
#import libs
import json
import ast

In [10]:
json_cols = ['belongs_to_collection', 'genres', 'production_companies'
            , 'production_countries', 'spoken_languages']

In [11]:
df['belongs_to_collection'][0]
# stringfied json column

"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"

In [12]:
json1 = '{"dog": 3, "cat": 5}'
json1

'{"dog": 3, "cat": 5}'

In [13]:
ast.literal_eval(json1)

{'dog': 3, 'cat': 5}

In [14]:
df['genres'].apply(ast.literal_eval)[0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [15]:
df_genres = df['genres'].apply(ast.literal_eval)
df_genres

0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                           [{'id': 35, 'name': 'Comedy'}]
                               ...
45461    [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                        [{'id': 18, 'name': 'Drama'}]
45463    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                   []
45465                                                   []
Name: genres, Length: 45466, dtype: object

In [16]:
# necessary lib
import numpy as np

In [17]:
df['belongs_to_collection'][0]

"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}"

In [18]:
# check whether the Elements is Instance of str 
df['belongs_to_collection'].apply(lambda x: isinstance(x, str))

0         True
1        False
2         True
3        False
4         True
         ...
45461    False
45462    False
45463    False
45464    False
45465    False
Name: belongs_to_collection, Length: 45466, dtype: bool

In [19]:
df['belongs_to_collection'] = df['belongs_to_collection'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

In [20]:
df['belongs_to_collection'][0]

{'id': 10194,
 'name': 'Toy Story Collection',
 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg',
 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}

In [21]:
# check the type of first record
type(df['belongs_to_collection'][0])

dict

In [22]:
# check how its look like
df['spoken_languages'][0]

"[{'iso_639_1': 'en', 'name': 'English'}]"

In [23]:
# check the type of first record of this col
type(df['spoken_languages'][0])

str

In [24]:
df['spoken_languages'] = df['spoken_languages'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

In [25]:
df['spoken_languages'][0]

[{'iso_639_1': 'en', 'name': 'English'}]

In [26]:
type(df['spoken_languages'][0])

list

In [27]:
# check the status of first record
df['production_countries'][0]

"[{'iso_3166_1': 'US', 'name': 'United States of America'}]"

In [28]:
# check the type of first record
type(df['production_countries'][0])

str

In [29]:
df['production_countries'] = df['production_countries'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

In [30]:
# check how first records looks like
df['production_countries'][0]

[{'iso_3166_1': 'US', 'name': 'United States of America'}]

In [31]:
# check the type of first record of this col
type(df['production_countries'][0])

list

In [32]:
# check first record to see how its look like
df['production_companies'][0]

"[{'name': 'Pixar Animation Studios', 'id': 3}]"

In [33]:
# check type of it
type(df['production_companies'][0])

str

In [34]:
df['production_companies'] = df['production_companies'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

In [35]:
# check first record again 
df['production_companies'][0]

[{'name': 'Pixar Animation Studios', 'id': 3}]

In [36]:
# check type of first record
type(df['production_companies'][0])

list

In [37]:
df['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [38]:
type(df['genres'][0])

str

In [39]:
df['genres'] = df['genres'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

In [40]:
# check frist record again
df['genres'][0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [41]:
type(df['genres'][0])

list

In [42]:
df.head()

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4494 non-null   object
 1   budget                 45466 non-null  object
 2   genres                 45466 non-null  object
 3   id                     45466 non-null  object
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45461 non-null  object
 7   poster_path            45080 non-null  object
 8   production_companies   45463 non-null  object
 9   production_countries   45463 non-null  object
 10  release_date           45379 non-null  object
 11  revenue                45460 non-null  float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       45460 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: float64(4), object(15)
memory usage: 6.6+ MB

In [44]:
df['belongs_to_collection'] = df['belongs_to_collection'].apply(lambda x: x['name'] if isinstance(x, dict) else np.nan)

In [45]:
df['belongs_to_collection'].value_counts(dropna = False).head(20)

belongs_to_collection
NaN                                       40975
The Bowery Boys                              29
Totò Collection                              27
James Bond Collection                        26
Zatôichi: The Blind Swordsman                26
The Carry On Collection                      25
Pokémon Collection                           22
Charlie Chan (Sidney Toler) Collection       21
Godzilla (Showa) Collection                  16
Charlie Chan (Warner Oland) Collection       15
Dragon Ball Z (Movie) Collection             15
Uuno Turhapuro                               15
Monster High Collection                      14
The Land Before Time Collection              14
George Carlin Comedy Collection              13
Sharpe Collection                            13
Friday the 13th Collection                   12
The Amityville Horror Collection             12
Johan Falk GSI Collection                    12
Sherlock Holmes (1939 series)                12
Name: count, dtype: int64

In [46]:
# check the first row
df['genres'][0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [47]:
df['genres'] = df['genres'].apply(lambda x: "|".join(i['name'] for i in x))

In [48]:
# check the frist row again
df['genres'][0]

'Animation|Comedy|Family'

In [49]:
df['genres'].value_counts(dropna = False).head(20)

genres
Drama                   5000
Comedy                  3621
Documentary             2723
                        2442
Drama|Romance           1301
Comedy|Drama            1135
Horror                   974
Comedy|Romance           930
Comedy|Drama|Romance     593
Drama|Comedy             532
Horror|Thriller          528
Drama|Thriller           497
Thriller                 465
Crime|Drama              430
Romance|Drama            343
Western                  318
Action|Thriller          301
Drama|Foreign            283
Action                   278
Drama|History            267
Name: count, dtype: int64

In [50]:
df['genres'].replace("", np.nan , inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\3329461508.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['genres'].replace("", np.nan , inplace = True)

In [51]:
df['genres'].value_counts(dropna = False).head(20)

genres
Drama                   5000
Comedy                  3621
Documentary             2723
NaN                     2442
Drama|Romance           1301
Comedy|Drama            1135
Horror                   974
Comedy|Romance           930
Comedy|Drama|Romance     593
Drama|Comedy             532
Horror|Thriller          528
Drama|Thriller           497
Thriller                 465
Crime|Drama              430
Romance|Drama            343
Western                  318
Action|Thriller          301
Drama|Foreign            283
Action                   278
Drama|History            267
Name: count, dtype: int64

In [52]:
df['spoken_languages'][0]

[{'iso_639_1': 'en', 'name': 'English'}]

In [53]:
df['spoken_languages'] = df['spoken_languages'].apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

In [54]:
df['spoken_languages'].value_counts(dropna = False).head()

spoken_languages
English     22395
             3952
Français     1853
日本語          1289
Italiano     1218
Name: count, dtype: int64

In [55]:
df['spoken_languages'].replace("", np.nan , inplace= True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\686351382.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['spoken_languages'].replace("", np.nan , inplace= True)

In [56]:
df['spoken_languages'].value_counts(dropna = False).head(20)

spoken_languages
English             22395
NaN                  3958
Français             1853
日本語                  1289
Italiano             1218
Español               902
Pусский               807
Deutsch               762
English|Français      681
English|Español       572
हिन्दी                481
English|Deutsch       462
한국어/조선말               425
普通话                   347
English|Italiano      326
svenska               311
No Language           303
Português             275
suomi                 275
Polski                213
Name: count, dtype: int64

In [57]:
df['production_countries'][0]

[{'iso_3166_1': 'US', 'name': 'United States of America'}]

In [58]:
df['production_countries'] = df['production_countries'].apply(lambda x : "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

In [59]:
df['production_countries'].value_counts(dropna = False).head(20)

production_countries
United States of America                   17851
                                            6282
United Kingdom                              2238
France                                      1654
Japan                                       1356
Italy                                       1030
Canada                                       840
Germany                                      749
India                                        735
Russia                                       735
United Kingdom|United States of America      569
South Korea                                  432
Spain                                        398
Hong Kong                                    365
Canada|United States of America              365
Australia                                    336
Sweden                                       332
Finland                                      271
France|Italy                                 235
Poland                                       214
Name: count, dtype: int64

In [60]:
df['production_countries'].replace("", np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\1927014743.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['production_countries'].replace("", np.nan, inplace = True)

In [61]:
df['production_countries'].value_counts(dropna = False).head(20)

production_countries
United States of America                   17851
NaN                                         6288
United Kingdom                              2238
France                                      1654
Japan                                       1356
Italy                                       1030
Canada                                       840
Germany                                      749
Russia                                       735
India                                        735
United Kingdom|United States of America      569
South Korea                                  432
Spain                                        398
Hong Kong                                    365
Canada|United States of America              365
Australia                                    336
Sweden                                       332
Finland                                      271
France|Italy                                 235
Poland                                       214
Name: count, dtype: int64

In [62]:
df['production_companies'][0:5]

0       [{'name': 'Pixar Animation Studios', 'id': 3}]
1    [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2    [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3    [{'name': 'Twentieth Century Fox Film Corporat...
4    [{'name': 'Sandollar Productions', 'id': 5842}...
Name: production_companies, dtype: object

In [63]:
df['production_companies'] = df['production_companies'].apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

In [64]:
df['production_companies'].value_counts(dropna = False).head(20)

production_companies
                                          11875
Metro-Goldwyn-Mayer (MGM)                   742
Warner Bros.                                540
Paramount Pictures                          505
Twentieth Century Fox Film Corporation      439
Universal Pictures                          320
RKO Radio Pictures                          247
Columbia Pictures Corporation               207
Columbia Pictures                           146
Mosfilm                                     145
Walt Disney Pictures                         85
Universal International Pictures (UI)        82
New Line Cinema                              75
Walt Disney Productions                      75
Shaw Brothers                                71
Touchstone Pictures                          70
Toho Company                                 65
TriStar Pictures                             62
Orion Pictures                               61
Hammer Film Productions                      60
Name: count, dtype: int64

In [65]:
df['production_companies'].replace("", np.nan, inplace = True)
df['production_companies'].value_counts(dropna = False).head(20)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\3377705862.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['production_companies'].replace("", np.nan, inplace = True)

production_companies
NaN                                       11881
Metro-Goldwyn-Mayer (MGM)                   742
Warner Bros.                                540
Paramount Pictures                          505
Twentieth Century Fox Film Corporation      439
Universal Pictures                          320
RKO Radio Pictures                          247
Columbia Pictures Corporation               207
Columbia Pictures                           146
Mosfilm                                     145
Walt Disney Pictures                         85
Universal International Pictures (UI)        82
Walt Disney Productions                      75
New Line Cinema                              75
Shaw Brothers                                71
Touchstone Pictures                          70
Toho Company                                 65
TriStar Pictures                             62
Orion Pictures                               61
Hammer Film Productions                      60
Name: count, dtype: int64

In [66]:
df.isna().sum()

belongs_to_collection    40975
budget                       0
genres                    2442
id                           0
original_language           11
overview                   954
popularity                   5
poster_path                386
production_companies     11881
production_countries      6288
release_date                87
revenue                      6
runtime                    263
spoken_languages          3958
status                      87
tagline                  25054
title                        6
vote_average                 6
vote_count                   6
dtype: int64

In [67]:
# original dataframe
pd.read_csv('movies_metadata.csv', low_memory= False).isna().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget                 45466 non-null  object
 2   genres                 43024 non-null  object
 3   id                     45466 non-null  object
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45461 non-null  object
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45379 non-null  object
 11  revenue                45460 non-null  float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: float64(4), object(15)
memory usage: 6.6+ MB

In [69]:
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')

In [70]:
df['budget'] = df['budget'].replace(0, np.nan)

In [71]:
df['budget'].value_counts(dropna = False)

budget
NaN            36576
5000000.0        286
10000000.0       259
20000000.0       243
2000000.0        242
               ...
152000000.0        1
1500.0             1
82000.0            1
1282545.0          1
2153912.0          1
Name: count, Length: 1223, dtype: int64

In [72]:
df['budget'] = df['budget'].div(1000000)

In [73]:
df['budget'].value_counts(dropna = False)

budget
NaN           36576
5.000000        286
10.000000       259
20.000000       243
2.000000        242
              ...
152.000000        1
0.001500          1
0.082000          1
1.282545          1
2.153912          1
Name: count, Length: 1223, dtype: int64

In [74]:
df['revenue'].value_counts(dropna = False)

revenue
0.0           38052
12000000.0       20
11000000.0       19
10000000.0       19
2000000.0        18
              ...
320395.0          1
50656.0           1
1328612.0         1
1268793.0         1
1413000.0         1
Name: count, Length: 6864, dtype: int64

In [75]:
df['revenue'] = df['revenue'].replace(0, np.nan)
df['revenue'] = df['revenue'].div(1000000)

In [76]:
df.rename(columns={'revenue' : 'revenue_musd', 'budget' : 'budget_musd'}, inplace = True)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object
 3   id                     45466 non-null  object
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45461 non-null  object
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45379 non-null  object
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: float64(5), object(14)
memory usage: 6.6+ MB

In [78]:
df['runtime'].value_counts(dropna = False).head(20)

runtime
90.0     2556
0.0      1558
100.0    1470
95.0     1412
93.0     1214
96.0     1104
92.0     1080
94.0     1062
91.0     1057
88.0     1032
97.0     1027
85.0     1024
98.0     1019
105.0    1002
89.0      958
87.0      919
110.0     850
86.0      846
99.0      794
102.0     791
Name: count, dtype: int64

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object
 3   id                     45466 non-null  object
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45461 non-null  object
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45379 non-null  object
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: float64(5), object(14)
memory usage: 6.6+ MB

In [80]:
df['id'] = pd.to_numeric(df['id'], errors = 'coerce')

In [81]:
df['id'].value_counts(dropna = False).head(20)

id
141971.0    3
NaN         3
69234.0     2
13209.0     2
109962.0    2
132641.0    2
105045.0    2
15028.0     2
14788.0     2
4912.0      2
168538.0    2
97995.0     2
22649.0     2
12600.0     2
10991.0     2
5511.0      2
159849.0    2
152795.0    2
11115.0     2
99080.0     2
Name: count, dtype: int64

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object
 3   id                     45463 non-null  float64
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45461 non-null  object
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45379 non-null  object
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: float64(6), object(13)
memory usage: 6.6+ MB

In [83]:
df['popularity'] = pd.to_numeric(df['popularity'], errors = 'coerce')

In [84]:
df['popularity'].value_counts(dropna = False).head(20)

popularity
0.000000    66
0.000001    56
0.000308    43
0.000220    40
0.000844    38
0.001177    38
0.000578    38
0.002001    28
0.003013    21
0.003530    19
0.001393    19
0.002353    18
0.036471    18
0.000603    16
0.001586    15
0.004425    14
0.000431    13
0.001021    13
0.004706    12
0.001247    11
Name: count, dtype: int64

In [85]:
df['vote_count'].value_counts(dropna = False).head(20)

vote_count
1.0     3264
2.0     3132
0.0     2899
3.0     2787
4.0     2480
5.0     2097
6.0     1747
7.0     1570
8.0     1359
9.0     1194
10.0    1171
11.0     944
12.0     859
13.0     733
14.0     700
15.0     674
16.0     601
17.0     554
18.0     497
20.0     463
Name: count, dtype: int64

In [86]:
df['vote_average'].value_counts(dropna = False).head(20)

vote_average
0.0    2998
6.0    2468
5.0    2001
7.0    1886
6.5    1722
6.3    1603
5.5    1381
5.8    1369
6.4    1350
6.7    1342
6.8    1324
6.1    1281
6.6    1263
6.2    1253
5.9    1196
5.3    1082
5.7    1046
6.9    1037
5.6    1006
7.3    1000
Name: count, dtype: int64

In [87]:
df.loc[df['vote_count'] == 0 , 'vote_count']

83       0.0
107      0.0
126      0.0
132      0.0
137      0.0
        ...
45432    0.0
45434    0.0
45452    0.0
45464    0.0
45465    0.0
Name: vote_count, Length: 2899, dtype: float64

In [88]:
# check how release_date columns is look like
df['release_date'][0]

'1995-10-30'

In [89]:
df['release_date'] = pd.to_datetime(df['release_date'], errors = 'coerce')

In [90]:
df['release_date'].value_counts(dropna = False).head(10)

release_date
2008-01-01    136
2009-01-01    121
2007-01-01    118
2005-01-01    111
2006-01-01    101
2002-01-01     96
2004-01-01     90
NaT            90
2001-01-01     84
2003-01-01     76
Name: count, dtype: int64

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object
 3   id                     45463 non-null  float64
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45460 non-null  float64
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45376 non-null  datetime64[ns]
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 6.6+ MB

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object
 3   id                     45463 non-null  float64
 4   original_language      45455 non-null  object
 5   overview               44512 non-null  object
 6   popularity             45460 non-null  float64
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45376 non-null  datetime64[ns]
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20412 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 6.6+ MB

In [93]:
df['original_language'].value_counts(dropna = False).head(10)

original_language
en    32269
fr     2438
it     1529
ja     1350
de     1080
es      994
ru      826
hi      508
ko      444
zh      409
Name: count, dtype: int64

In [94]:
df['title']

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3                  Waiting to Exhale
4        Father of the Bride Part II
                    ...
45461                         Subdue
45462            Century of Birthing
45463                       Betrayal
45464               Satan Triumphant
45465                       Queerama
Name: title, Length: 45466, dtype: object

In [95]:
df['title'].value_counts(dropna = False).head(10)

title
Cinderella              11
Alice in Wonderland      9
Hamlet                   9
Beauty and the Beast     8
Les Misérables           8
The Three Musketeers     7
A Christmas Carol        7
Blackout                 7
Treasure Island          7
Jane Eyre                6
Name: count, dtype: int64

In [96]:
df['overview'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [97]:
df['overview'].value_counts(dropna = False).head(10)

overview
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               954
No overview found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                133
No Overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5
Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.                                                                                                                                                                                                                                                                                                                                                                                                                              3
King Lear, old and tired, divides his kingdom among his daughters, giving great importance to their protestations of love for him. When Cordelia, youngest and most honest, refuses to idly flatter the old man in return for favor, he banishes her and turns for support to his remaining daughters. But Goneril and Regan have no love for him and instead plot to take all his power from him. In a parallel, Lear's loyal courtier Gloucester favors his illegitimate son Edmund after being told lies about his faithful son Edgar. Madness and tragedy befall both ill-starred fathers.      3
Released                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3
A few funny little novels about different aspects of life.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
No movie overview available.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
Adaptation of the Jane Austen novel.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
Name: count, dtype: int64

In [98]:
df['overview'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [99]:
df['overview'].replace('No overview found.', np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\1603602739.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overview'].replace('No overview found.', np.nan, inplace = True)

In [100]:
df['overview'].value_counts(dropna = False).head(20)

overview
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1087
No Overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5
Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3
King Lear, old and tired, divides his kingdom among his daughters, giving great importance to their protestations of love for him. When Cordelia, youngest and most honest, refuses to idly flatter the old man in return for favor, he banishes her and turns for support to his remaining daughters. But Goneril and Regan have no love for him and instead plot to take all his power from him. In a parallel, Lear's loyal courtier Gloucester favors his illegitimate son Edmund after being told lies about his faithful son Edgar. Madness and tragedy befall both ill-starred fathers.                                                                                                                                                                                                                                                                      3
Released                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3
A few funny little novels about different aspects of life.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
No movie overview available.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
Adaptation of the Jane Austen novel.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
Until now, Zak Gibbs' greatest challenge has been to find a way to buy a car. But when he discovers an odd wristwatch amidst his father's various inventions and slips it on -- something very strange happens. The world around him seems to come to a stop, everything and everybody frozen in time. Zak quickly learns how to manipulate the device and he and his quick-witted and beautiful new friend, Francesca, start to have some real fun.                                                                                                                                                                                                                                                                                                                                                                                                                2
British nurse Catherine Barkley (Helen Hayes) and American Lieutenant Frederic Henry (Gary Cooper) fall in love during the First World War in Italy. Eventually separated by Frederic's transfer, tremendous challenges and difficult decisions face each, as the war rages on. Academy Awards winner for Best Cinematography and for Best Sound, Recording. Nominated for Best Picture and for Best Art Direction.                                                                                                                                                                                                                                                                                                                                                                                                                                                 2
In feudal India, a warrior (Khan) who renounces his role as the longtime enforcer to a local lord becomes the prey in a murderous hunt through the Himalayan mountains.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2
Ten years into a marriage, the wife is disappointed by the husband's lack of financial success, meaning she has to work and can't treat herself and the husband finds the wife slovenly and mean-spirited: she neither cooks not cleans particularly well and is generally disagreeable. In turn, he alternately ignores her and treats her as a servant. Neither is particularly happy, not helped by their unsatisfactory lodgers. The husband is easily seduced by an ex-colleague, a widow with a small child who needs some security, and considers leaving his wife.                                                                                                                                                                                                                                                                                          2
Originally called White Thunder, American producer Varick Frissell's 1931 film was inspired by his love for the Canadian Arctic Circle. Set in a beautifully black-and-white filmed Newfoundland, it is the story of a rivalry between two seal hunters that plays out on the ice floes during a hunt. Unsatisfied with the first cut, Frissell arranged for the crew to accompany an actual Newfoundland seal hunt on The SS Viking, on which an explosion of dynamite (carried regularly at the time on Arctic ships to combat ice jams) killed many members of the crew, including Frissell. The film was renamed in honor of the dead.                                                                                                                                                                                                                          2
Television made him famous, but his biggest hits happened off screen. Television producer by day, CIA assassin by night, Chuck Barris was recruited by the CIA at the height of his TV career and trained to become a covert operative. Or so Barris said.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2
Using personal stories, this powerful documentary illuminates the plight of the 49 million Americans struggling with food insecurity. A single mother, a small-town policeman and a farmer are among those for whom putting food on the table is a daily battle.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
All your favorite Pokémon characters are back, and are joined for the first time by the legendary Pokémon Celebi and Suicune, in this latest exciting Pokémon adventure! In order to escape a greedy Pokémon hunter, Celebi must use the last of its energy to travel through time to the present day. Celebi brings along Sammy, a boy who had been trying to protect it. Along with Ash, Pikachu, and the rest of the gang, Sammy and Celebi encounter an enemy far more advanced than the hunter left behind in the past. This new enemy possesses a Pokéball called a “Dark Ball,” which transforms the Pokémon it captures into evil and far stronger creatures. When Celebi is captured, the fate of the entire forest is threatened. Let POKÉMON 4EVER transport you to a world of adventure as Ash, Suicune and the rest take action to save the day!       2
The Kingdom of the People of the Vale once ruled over the land, but now all that remains is the Sword of the Vale. in the city of Eindoak. Ash, Iris, and Cilan arrive in Eindoak during a harvest festival's Pokémon Tournament and meet the legendary Pokémon Victini who wishes to share its powers of victory to someone. Elsewhere in the city, a descendant of the People of the Vale named Damon has arrived who seeks to revive the kingdom's power with the Sword of the Vale, bringing them back into power over the land, and Ash and his friends must stop him before he destroys the land along with Victini.                                                                                                                                                                                                                                          2
Since women are banned from soccer matches, Iranian females masquerade as males so they can slip into Tehran's stadium to see the game between Iran and Bahrain. The ones who are caught and arrested are taken to a holding area and guarded by soldiers. One sympathetic soldier agrees to watch the game through a peephole and recount the action to the impatient fans.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
Former Danish servicemen Lars and Jimmy are thrown together while training in a neo-Nazi group. Moving from hostility through grudging admiration to friendship and finally passion, events take a darker turn when their illicit relationship is uncovered.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
Name: count, dtype: int64

In [101]:
df['overview'].replace('No Overview', np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\4189228509.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overview'].replace('No Overview', np.nan, inplace = True)

In [102]:
df['overview'].replace('No movie overview available.', np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\797338525.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overview'].replace('No movie overview available.', np.nan, inplace = True)

In [103]:
df['overview'].replace(" ", np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\424095031.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overview'].replace(" ", np.nan, inplace = True)

In [104]:
df['overview'].replace('No overview yet', np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\2422783915.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overview'].replace('No overview yet', np.nan, inplace = True)

In [105]:
df['overview'].value_counts(dropna = False).head(20)

overview
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1102
Released                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3
Recovering from a nail gun shot to the head and 13 months of coma, doctor Pekka Valinta starts to unravel the mystery of his past, still suffering from total amnesia.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3
King Lear, old and tired, divides his kingdom among his daughters, giving great importance to their protestations of love for him. When Cordelia, youngest and most honest, refuses to idly flatter the old man in return for favor, he banishes her and turns for support to his remaining daughters. But Goneril and Regan have no love for him and instead plot to take all his power from him. In a parallel, Lear's loyal courtier Gloucester favors his illegitimate son Edmund after being told lies about his faithful son Edgar. Madness and tragedy befall both ill-starred fathers.                                                                                                                                                                                                                                                                      3
A few funny little novels about different aspects of life.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
Adaptation of the Jane Austen novel.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
Television made him famous, but his biggest hits happened off screen. Television producer by day, CIA assassin by night, Chuck Barris was recruited by the CIA at the height of his TV career and trained to become a covert operative. Or so Barris said.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2
No overview yet.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
All your favorite Pokémon characters are back, and are joined for the first time by the legendary Pokémon Celebi and Suicune, in this latest exciting Pokémon adventure! In order to escape a greedy Pokémon hunter, Celebi must use the last of its energy to travel through time to the present day. Celebi brings along Sammy, a boy who had been trying to protect it. Along with Ash, Pikachu, and the rest of the gang, Sammy and Celebi encounter an enemy far more advanced than the hunter left behind in the past. This new enemy possesses a Pokéball called a “Dark Ball,” which transforms the Pokémon it captures into evil and far stronger creatures. When Celebi is captured, the fate of the entire forest is threatened. Let POKÉMON 4EVER transport you to a world of adventure as Ash, Suicune and the rest take action to save the day!       2
The Kingdom of the People of the Vale once ruled over the land, but now all that remains is the Sword of the Vale. in the city of Eindoak. Ash, Iris, and Cilan arrive in Eindoak during a harvest festival's Pokémon Tournament and meet the legendary Pokémon Victini who wishes to share its powers of victory to someone. Elsewhere in the city, a descendant of the People of the Vale named Damon has arrived who seeks to revive the kingdom's power with the Sword of the Vale, bringing them back into power over the land, and Ash and his friends must stop him before he destroys the land along with Victini.                                                                                                                                                                                                                                          2
Since women are banned from soccer matches, Iranian females masquerade as males so they can slip into Tehran's stadium to see the game between Iran and Bahrain. The ones who are caught and arrested are taken to a holding area and guarded by soldiers. One sympathetic soldier agrees to watch the game through a peephole and recount the action to the impatient fans.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
When Molly Hale's sadness of her father's disappearance get to her, she unknowingly uses the Unown to create her own dream world along with Entei, who she believes to be her father. When Entei kidnaps Ash's mom, Ash along with Misty & Brock invade the mansion looking for his mom and trying to stop the mysteries of Molly's Dream World and Entei!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2
Using personal stories, this powerful documentary illuminates the plight of the 49 million Americans struggling with food insecurity. A single mother, a small-town policeman and a farmer are among those for whom putting food on the table is a daily battle.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
Former Danish servicemen Lars and Jimmy are thrown together while training in a neo-Nazi group. Moving from hostility through grudging admiration to friendship and finally passion, events take a darker turn when their illicit relationship is uncovered.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2
When a comet strikes Earth and kicks up a cloud of toxic dust, hundreds of humans join the ranks of the living dead. But there's bad news for the survivors: The newly minted zombies are hell-bent on eradicating every last person from the planet. For the few human beings who remain, going head to head with the flesh-eating fiends is their only chance for long-term survival. Yet their battle will be dark and cold, with overwhelming odds.                                                                                                                                                                                                                                                                                                                                                                                                             2
As an ex-gambler teaches a hot-shot college kid some things about playing cards, he finds himself pulled into the world series of poker, where his protégé is his toughest competition.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2
Adventurer Allan Quartermain leads an expedition into uncharted African territory in an attempt to locate an explorer who went missing during his search for the fabled diamond mines of King Solomon.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2
After breaking a mirror in his home, superstitious Max tries to avoid situations which could bring bad luck but in doing so, causes himself the worst luck imaginable.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2
Two literary women compete for 20 years: one writes for the critics; the other one, to get rich.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
Wilbur the pig is scared of the end of the season, because he knows that come that time, he will end up on the dinner table. He hatches a plan with Charlotte, a spider that lives in his pen, to ensure that this will never happen.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2
Name: count, dtype: int64

In [106]:
df['tagline'].value_counts(dropna = False).head(50)

tagline
NaN                                                                                     25054
Based on a true story.                                                                      7
-                                                                                           4
Be careful what you wish for.                                                               4
Trust no one.                                                                               4
Some doors should never be opened.                                                          3
Drama                                                                                       3
Know Your Enemy                                                                             3
Which one is the first to return - memory or the murderer?                                  3
There are two sides to every love story.                                                    3
The end is near.                                                                            3
A Love Story                                                                                3
There is no turning back                                                                    3
Who is John Galt?                                                                           3
How far would you go?                                                                       3
Classic Albums                                                                              3
Documentary                                                                                 3
...Fear is the Message!                                                                     2
Some things are worth fighting for.                                                         2
Inspired by a true story                                                                    2
Der deutsche Millionen-Film!                                                                2
It's time to take a stand.                                                                  2
What you know about fear... doesn't even come close.                                        2
The first to die were the lucky ones!                                                       2
Every second counts.                                                                        2
One ordinary couple. One little white lie.                                                  2
Trust No One                                                                                2
Adapt or die.                                                                               2
An American Tragedy                                                                         2
How Miami became the cocaine capital of the United States!                                  2
Nothing is more dangerous than the truth.                                                   2
Some secrets are better left buried.                                                        2
Meet Fievel. In his search to find his family, he discovered America.                       2
Love never dies.                                                                            2
Every family has a secret.                                                                  2
Actually produced during the Great Newfoundland Seal Hunt and You see the REAL thing        2
Worlds Collide                                                                              2
Terror runs deep.                                                                           2
Evil will rise.                                                                             2
The end of the world is just the beginning.                                                 2
The timeless tale of a special place where magic, hope and love grow.                       2
One Nation. Underfed.                                                                       2
Based on the incredible true story.                                                         2
There is no solitude greater than that of the Samurai                                       2
Fight Fire With Fire                                                                        2
Inspect the unexpected.                                                                     2
Once upon a time...                                                                         2
Pokémon: Spell of the Unknown                                                               2
Victor Crowley Lives Again                                                                  2
Some loves are meant to be. This one, not so much.                                          2
Name: count, dtype: int64

In [107]:
df['tagline'].replace('-', np.nan, inplace = True)

C:\Users\tanis\AppData\Local\Temp\ipykernel_20144\4136611573.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tagline'].replace('-', np.nan, inplace = True)

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget_musd            8890 non-null   float64
 2   genres                 43024 non-null  object
 3   id                     45463 non-null  float64
 4   original_language      45455 non-null  object
 5   overview               44364 non-null  object
 6   popularity             45460 non-null  float64
 7   poster_path            45080 non-null  object
 8   production_companies   33585 non-null  object
 9   production_countries   39178 non-null  object
 10  release_date           45376 non-null  datetime64[ns]
 11  revenue_musd           7408 non-null   float64
 12  runtime                45203 non-null  float64
 13  spoken_languages       41508 non-null  object
 14  status                 45379 non-null  object
 15  tagline                20408 non-null  object
 16  title                  45460 non-null  object
 17  vote_average           45460 non-null  float64
 18  vote_count             45460 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 6.6+ MB

In [109]:
df[df.duplicated(keep = False)].sort_values(by = 'id')

,belongs_to_collection,budget_musd,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue_musd,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
7345,NaN,NaN,Crime|Drama|Thriller,5511.0,fr,Hitman Jef Costello is a perfectionist who alw...,9.091288,/cvNW8IXigbaMNo4gKEIps0NGnhA.jpg,Fida cinematografica|Compagnie Industrielle et...,France|Italy,1967-10-25,0.039481,105.0,Français,Released,There is no solitude greater than that of the ...,Le Samouraï,7.9,187.0
9165,NaN,NaN,Crime|Drama|Thriller,5511.0,fr,Hitman Jef Costello is a perfectionist who alw...,9.091288,/cvNW8IXigbaMNo4gKEIps0NGnhA.jpg,Fida cinematografica|Compagnie Industrielle et...,France|Italy,1967-10-25,0.039481,105.0,Français,Released,There is no solitude greater than that of the ...,Le Samouraï,7.9,187.0
14012,NaN,NaN,Comedy|Drama,11115.0,en,As an ex-gambler teaches a hot-shot college ki...,6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,Andertainment Group|Crescent City Pictures|Tag...,United States of America,2008-01-29,NaN,85.0,English,Released,NaN,Deal,5.2,22.0
24844,NaN,NaN,Comedy|Drama,11115.0,en,As an ex-gambler teaches a hot-shot college ki...,6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,Andertainment Group|Crescent City Pictures|Tag...,United States of America,2008-01-29,NaN,85.0,English,Released,NaN,Deal,5.2,22.0
22151,NaN,NaN,Action|Horror|Science Fiction,18440.0,en,When a comet strikes Earth and kicks up a clou...,1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,NaN,United States of America,2007-01-01,NaN,89.0,English,Released,NaN,Days of Darkness,5.0,5.0
14000,NaN,NaN,Action|Horror|Science Fiction,18440.0,en,When a comet strikes Earth and kicks up a clou...,1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,NaN,United States of America,2007-01-01,NaN,89.0,English,Released,NaN,Days of Darkness,5.0,5.0
9327,NaN,NaN,Adventure|Animation|Drama|Action|Foreign,23305.0,en,"In feudal India, a warrior (Khan) who renounce...",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,Filmfour,France|Germany|India|United Kingdom,2001-09-23,NaN,86.0,हिन्दी,Released,NaN,The Warrior,6.3,15.0
8068,NaN,NaN,Adventure|Animation|Drama|Action|Foreign,23305.0,en,"In feudal India, a warrior (Khan) who renounce...",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,Filmfour,France|Germany|India|United Kingdom,2001-09-23,NaN,86.0,हिन्दी,Released,NaN,The Warrior,6.3,15.0
17229,NaN,NaN,Drama,25541.0,da,Former Danish servicemen Lars and Jimmy are th...,2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,NaN,Sweden|Denmark,2009-10-21,NaN,90.0,Dansk,Released,NaN,Brotherhood,7.1,21.0
23044,NaN,NaN,Drama,25541.0,da,Former Danish servicemen Lars and Jimmy are th...,2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,NaN,Sweden|Denmark,2009-10-21,NaN,90.0,Dansk,Released,NaN,Brotherhood,7.1,21.0
15702,NaN,NaN,Drama|Foreign,42495.0,en,"King Lear, old and tired, divides his kingdom ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,Royal Shakespeare Company|Laterna Film|Athena ...,Denmark|United Kingdom,1971-02-04,NaN,137.0,English,Rumored,NaN,King Lear,8.0,3.0
29374,NaN,NaN,Drama|Foreign,42495.0,en,"King Lear, old and tired, divides his kingdom ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,Royal Shakespeare Company|Laterna Film|Athena ...,Denmark|United Kingdom,1971-02-04,NaN,137.0,English,Rumored,NaN,King Lear,8.0,3.0
40276,NaN,NaN,Comedy,97995.0,en,"After breaking a mirror in his home, superstit...",0.141558,/4J6Ai4C5YRgfRUTlirrJ7QsmJKU.jpg,Max Linder Productions,United States of America,1921-02-06,NaN,62.0,English,Released,NaN,Seven Years Bad Luck,5.6,4.0
13946,NaN,NaN,Comedy,97995.0,en,"After breaking a mirror in his home, superstit...",0.141558,/4J6Ai4C5YRgfRUTlirrJ7QsmJKU.jpg,Max Linder Productions,United States of America,1921-02-06,NaN,62.0,English,Released,NaN,Seven Years Bad Luck,5.6,4.0
16167,NaN,NaN,Action|Drama|Romance|Adventure,99080.0,en,"Originally called White Thunder, American prod...",0.002362,/qenjwRvW9itR5pVp4CBkYfhVAOp.jpg,NaN,NaN,1931-06-21,NaN,70.0,English,Released,Actually produced during the Great Newfoundlan...,The Viking,0.0,0.0
38871,NaN,NaN,Action|Drama|Romance|Adventure,99080.0,en,"Originally called White Thunder, American prod...",0.002362,/qenjwRvW9itR5pVp4CBkYfhVAOp.jpg,NaN,NaN,1931-06-21,NaN,70.0,English,Released,Actually produced during the Great Newfoundlan...,The Viking,0.0,0.0
676,NaN,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinéma...,Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
1465,NaN,NaN,Drama|Romance,105045.0,de,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,Studio Babelsberg|Centre National de la Cinéma...,Germany,1995-02-16,NaN,115.0,Deutsch,Released,"A love, a hope, a wall.",The Promise,5.0,1.0
21165,NaN,NaN,Fantasy|Drama|Science Fiction,119916.0,en,"Prospero, the true Duke of Milan is now living...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,NaN,NaN,1980-02-27,NaN,123.0,NaN,Released,NaN,The Tempest,0.0,0.0
19890,NaN,NaN,Fantasy|Drama|Science Fiction,119916.0,en,"Prospero, the true Duke of Milan is now living...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,NaN,NaN,1980-02-27,NaN,123.0,NaN,Released,NaN,The Tempest,0.0,0.0
13261,NaN,NaN,Thriller|Mystery,141971.0,fi,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or t...,Blackout,6.7,3.0
16764,NaN,NaN,Thriller|Mystery,141971.0,fi,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or t...,Blackout,6.7,3.0
13375,NaN,NaN,Thriller|Mystery,141971.0,fi,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,Filmiteollisuus Fine,Finland,2008-12-26,NaN,108.0,suomi,Released,Which one is the first to return - memory or t...,Blackout,6.7,3.0
19925,NaN,NaN,Drama|Science Fiction|Animation,152795.0,en,More than two decades after catapulting to sta...,8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,Pandora Filmproduktion|Entre Chien et Loup|Opu...,Belgium|France|Germany|Israel|Luxembourg|Poland,2013-05-16,0.455815,122.0,English,Released,NaN,The Congress,6.4,165.0
21854,NaN,NaN,Drama|Science Fiction|Animation,152795.0,en,More than two decades after catapulting to sta...,8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,Pandora Filmproduktion|Entre Chien et Loup|Opu...,Belgium|France|Germany|Israel|Luxembourg|Poland,2013-05-16,0.455815,122.0,English,Released,NaN,The Congress,6.4,165.0
13220,Why We Fight,NaN,Documentary,159849.0,en,"The third film of Frank Capra's 'Why We Fight""...",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,NaN,United States of America,1943-01-01,NaN,57.0,English,Released,NaN,Why We Fight: Divide and Conquer,5.0,1.0
35798,Why We Fight,NaN,Documentary,159849.0,en,"The third film of Frank Capra's 'Why We Fight""...",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,NaN,United States of America,1943-01-01,NaN,57.0,English,Released,NaN,Why We Fight: Divide and Conquer,5.0,1.0
13603,NaN,NaN,Drama|Comedy,168538.0,en,"In Zola's Paris, an ingenue arrives at a tony ...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,Cannon Group|Metro-Goldwyn-Mayer (MGM),NaN,1983-06-13,NaN,92.0,NaN,Released,NaN,"Nana, the True Key of Pleasure",4.7,3.0
28860,NaN,NaN,Drama|Comedy,168538.0,en,"In Zola's Paris, an ingenue arrives at a tony ...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,Cannon Group|Metro-Goldwyn-Mayer (MGM),NaN,1983-06-13,NaN,92.0,NaN,Released,NaN,"Nana, the True Key of Pleasure",4.7,3.0
24164,NaN,NaN,Comedy|Drama,265189.0,sv,"While holidaying in the French Alps, a Swedish...",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,Motlys|Coproduction Office|Film i Väst,Norway|Sweden|France,2014-08-15,1.359497,118.0,Français|Norsk|svenska|English,Released,NaN,Force Majeure,6.8,255.0
45265,NaN,NaN,Comedy|Drama,265189.0,sv,"While holidaying in the French Alps, a Swedish...",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,Motlys|Coproduction Office|Film i Väst,Norway|Sweden|France,2014-08-15,1.359497,118.0,Français|Norsk|svenska|English,Released,NaN,Force Majeure,6.8,255.0
33184,NaN,0.98,Drama|Fantasy,298721.0,th,"In a hospital, ten soldiers are being treated ...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"Match Factory, The|Louverture Films|Tordenfilm...",United Kingdom|United States of America|France...,2015-09-02,NaN,122.0,English|ภาษาไทย,Released,NaN,Cemetery of Splendour,4.4,50.0
40040,NaN,0.98,Drama|Fantasy,298721.0,th,"In a hospital, ten soldiers are being treated ...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"Match Factory, The|Louverture Films|Tordenfilm...",United Kingdom|United States of America|France...,2015-09-02,NaN,122.0,English|ภาษาไทย,Released,NaN,Cemetery of Splendour,4.4,50.0

In [110]:
df.drop_duplicates(inplace = True)

In [111]:
df[df.duplicated(subset = 'id', keep= False)].sort_values(by = 'id')

,belongs_to_collection,budget_musd,genres,id,original_language,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue_musd,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
5865,NaN,30.000000,Comedy|Crime|Drama|Romance|Thriller,4912.0,en,"Television made him famous, but his biggest hi...",11.331072,/o3Im9nPLAgtlw1j2LtpMebAotSe.jpg,Miramax Films|Allied Filmmakers|Mad Chance,United States of America,2002-12-30,33.013805,113.0,English,Released,Some things are better left top secret.,Confessions of a Dangerous Mind,6.6,281.0
33826,NaN,30.000000,Comedy|Crime|Drama|Romance|Thriller,4912.0,en,"Television made him famous, but his biggest hi...",7.645827,/o3Im9nPLAgtlw1j2LtpMebAotSe.jpg,Miramax Films|Allied Filmmakers|Mad Chance,United States of America,2002-12-30,33.013805,113.0,English,Released,Some things are better left top secret.,Confessions of a Dangerous Mind,6.6,281.0
44821,Pokémon Collection,16.000000,Adventure|Fantasy|Animation|Action|Family,10991.0,ja,When Molly Hale's sadness of her father's disa...,6.480376,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,TV Tokyo|4 Kids Entertainment|Nintendo|Pikachu...,Japan,2000-07-08,68.411275,93.0,English,Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,6.0,144.0
4114,Pokémon Collection,16.000000,Adventure|Fantasy|Animation|Action|Family,10991.0,ja,When Molly Hale's sadness of her father's disa...,10.264597,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,TV Tokyo|4 Kids Entertainment|Nintendo|Pikachu...,Japan,2000-07-08,68.411275,93.0,English,Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,6.0,143.0
5535,Pokémon Collection,NaN,Adventure|Fantasy|Animation|Science Fiction|Fa...,12600.0,ja,"All your favorite Pokémon characters are back,...",7.072301,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,NaN,Japan|United States of America,2001-07-06,28.023563,75.0,日本語,Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,5.7,82.0
44826,Pokémon Collection,NaN,Adventure|Fantasy|Animation|Science Fiction|Fa...,12600.0,ja,"All your favorite Pokémon characters are back,...",6.080108,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,NaN,Japan|United States of America,2001-07-06,28.023563,75.0,日本語,Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,5.7,82.0
15765,NaN,0.002500,Drama|Comedy|Foreign,13209.0,fa,"Since women are banned from soccer matches, Ir...",1.529879,/nfkOkpudNNIjRrf0mTFVoiGzHyc.jpg,Jafar Panahi Film Productions,Iran,2006-05-26,NaN,93.0,فارسی,Released,NaN,Offside,6.7,27.0
11342,NaN,0.002500,Drama|Comedy|Foreign,13209.0,fa,"Since women are banned from soccer matches, Ir...",1.528960,/nfkOkpudNNIjRrf0mTFVoiGzHyc.jpg,Jafar Panahi Film Productions,Iran,2006-05-26,NaN,93.0,فارسی,Released,NaN,Offside,6.7,27.0
12066,NaN,1.600000,Drama|Crime|Mystery,14788.0,en,Set against the backdrop of a decaying Midwest...,3.008299,/w56oo9nREcF54sNXVYuE9QxZFjT.jpg,Magnolia Pictures|Extension 765,United States of America,2005-09-03,NaN,73.0,English,Released,NaN,Bubble,6.4,36.0
10419,NaN,1.600000,Drama|Crime|Mystery,14788.0,en,Set against the backdrop of a decaying Midwest...,3.185256,/w56oo9nREcF54sNXVYuE9QxZFjT.jpg,Magnolia Pictures|Extension 765,United States of America,2005-09-03,NaN,73.0,English,Released,NaN,Bubble,6.4,36.0
33743,NaN,26.000000,Adventure|Family|Science Fiction|Thriller,15028.0,en,"Until now, Zak Gibbs' greatest challenge has b...",4.920175,/xGhDPrBz9mJN8CsIjA23jQSd3sc.jpg,Paramount Pictures|Nickelodeon Movies|Valhalla...,United States of America,2002-03-17,38.793283,94.0,Český|English,Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers,4.9,90.0
5130,NaN,26.000000,Adventure|Family|Science Fiction|Thriller,15028.0,en,"Until now, Zak Gibbs' greatest challenge has b...",5.373623,/xGhDPrBz9mJN8CsIjA23jQSd3sc.jpg,Paramount Pictures|Nickelodeon Movies|Valhalla...,United States of America,2002-03-17,38.793283,94.0,Český|English,Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers,4.9,89.0
949,NaN,0.000004,Drama|Romance|War,22649.0,en,British nurse Catherine Barkley (Helen Hayes) ...,1.914697,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,Paramount Pictures,United States of America,1932-12-08,0.000025,89.0,English,Released,Every woman who has loved will understand,A Farewell to Arms,6.2,29.0
15074,NaN,0.000004,Drama|Romance|War,22649.0,en,British nurse Catherine Barkley (Helen Hayes) ...,2.411191,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,Paramount Pictures,United States of America,1932-12-08,0.000025,89.0,English,Released,Every woman who has loved will understand,A Farewell to Arms,6.2,29.0
9576,NaN,10.000000,Drama|Horror|Music|Romance|TV Movie,69234.0,en,Count de Chagnie has discovered Christine's si...,0.441872,/ole8e9YQwvHoKVpWO0lgfLFFemc.jpg,Beta Film|Reteitalia|TF1|Hexatel|Saban/Scheric...,France|Germany|Italy|United States of America,1990-03-18,NaN,168.0,English|Italiano,Released,NaN,The Phantom of the Opera,5.0,3.0
26625,NaN,10.000000,Drama|Horror|Music|Romance|TV Movie,69234.0,en,Count de Chagnie has discovered Christine's si...,0.438490,/ole8e9YQwvHoKVpWO0lgfLFFemc.jpg,Beta Film|Reteitalia|TF1|Hexatel|Saban/Scheric...,France|Germany|Italy|United States of America,1990-03-18,NaN,168.0,English|Italiano,Released,NaN,The Phantom of the Opera,5.0,3.0
11155,NaN,40.000000,Adventure|Drama,77221.0,en,"On the Arabian Peninsula in the 1930s, two war...",6.652197,/iQd7zWhSeCe3cgdPcLIDXjGfdzL.jpg,France 2 Cinéma|Quinta Communications|Carthago...,France|Italy|Qatar|Tunisia,2011-12-21,5.446000,130.0,English,Released,NaN,Black Gold,5.9,77.0
20843,NaN,40.000000,Adventure|Drama,77221.0,en,"On the Arabian Peninsula in the 1930s, two war...",6.475665,/iQd7zWhSeCe3cgdPcLIDXjGfdzL.jpg,France 2 Cinéma|Quinta Communications|Carthago...,France|Italy|Qatar|Tunisia,2011-12-21,5.446000,130.0,English,Released,NaN,Black Gold,5.9,77.0
21116,NaN,NaN,Documentary,84198.0,en,"Using personal stories, this powerful document...",1.673307,/jn8L1QdWWX5c0NUOLjzaSXtZrbt.jpg,NaN,United States of America,2012-03-22,NaN,84.0,English,Released,One Nation. Underfed.,A Place at the Table,6.9,7.0
2564,NaN,NaN,Documentary,84198.0,en,"Using personal stories, this powerful document...",0.501046,/jn8L1QdWWX5c0NUOLjzaSXtZrbt.jpg,NaN,United States of America,2012-03-22,NaN,84.0,English,Released,One Nation. Underfed.,A Place at the Table,6.9,7.0
5710,NaN,NaN,Drama,109962.0,en,Two literary women compete for 20 years: one w...,12.180836,/tOflyY8eUFWubLKJH7fKg4KwpCl.jpg,Metro-Goldwyn-Mayer (MGM)|Jaquet,United States of America,1981-09-23,NaN,115.0,English,Released,"From the very beginning, they knew they'd be f...",Rich and Famous,4.9,7.0
20899,NaN,NaN,Drama,109962.0,en,Two literary women compete for 20 years: one w...,10.396878,/tOflyY8eUFWubLKJH7fKg4KwpCl.jpg,Metro-Goldwyn-Mayer (MGM)|Jaquet,United States of America,1981-09-23,NaN,115.0,English,Released,"From the very beginning, they knew they'd be f...",Rich and Famous,4.9,7.0
23534,NaN,3.512454,Drama,110428.0,fr,"Winter, 1915. Confined by her family to an asy...",0.110065,/sGMPDg6je1zKi0TiX9b4pP6yN02.jpg,Canal+|Arte France Cinéma|3B Productions|C.R.R...,France,2013-03-13,0.115860,95.0,Français,Released,NaN,Camille Claudel 1915,7.0,20.0
4356,NaN,3.512454,Drama,110428.0,fr,"Winter, 1915. Confined by her family to an asy...",0.134014,/sGMPDg6je1zKi0TiX9b4pP6yN02.jpg,Canal+|Arte France Cinéma|3B Productions|C.R.R...,France,2013-03-13,0.115860,95.0,Français,Released,NaN,Camille Claudel 1915,7.0,20.0
838,NaN,NaN,Drama,132641.0,ja,"Ten years into a marriage, the wife is disappo...",0.096079,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,Toho Company,Japan,1953-04-29,NaN,89.0,日本語,Released,NaN,Wife,0.0,0.0
30001,NaN,NaN,Drama,132641.0,ja,"Ten years into a marriage, the wife is disappo...",0.619388,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,Toho Company,Japan,1953-04-29,NaN,89.0,日本語,Released,NaN,Wife,0.0,0.0
19730,NaN,NaN,Carousel Productions|Vision View Entertainment...,NaN,104.0,Released,NaN,Midnight Man,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,NaN,NaN,Aniplex|GoHands|BROSTA TV|Mardock Scramble Pro...,NaN,68.0,Released,NaN,Mardock Scramble: The Third Exhaust,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,NaN,NaN,Odyssey Media|Pulser Productions|Rogue State|T...,NaN,82.0,Released,NaN,Avalanche Sharks,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
df.drop_duplicates(subset = 'id', inplace = True)

In [113]:
df['id'].value_counts(dropna = False)

id
461257.0    1
862.0       1
8844.0      1
15602.0     1
31357.0     1
           ..
1408.0      1
10858.0     1
21032.0     1
12110.0     1
9087.0      1
Name: count, Length: 45434, dtype: int64

In [114]:
df['status'].value_counts()

status
Released           44985
Rumored              229
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: count, dtype: int64

In [115]:
df = df.loc[df['status'] == 'Released'].copy()

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44985 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4463 non-null   object
 1   budget_musd            8855 non-null   float64
 2   genres                 42601 non-null  object
 3   id                     44985 non-null  float64
 4   original_language      44975 non-null  object
 5   overview               43920 non-null  object
 6   popularity             44985 non-null  float64
 7   poster_path            44612 non-null  object
 8   production_companies   33357 non-null  object
 9   production_countries   38839 non-null  object
 10  release_date           44907 non-null  datetime64[ns]
 11  revenue_musd           7385 non-null   float64
 12  runtime                44734 non-null  float64
 13  spoken_languages       41110 non-null  object
 14  status                 44985 non-null  object
 15  tagline                20285 non-null  object
 16  title                  44985 non-null  object
 17  vote_average           44985 non-null  float64
 18  vote_count             44985 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 6.9+ MB

In [117]:
df.drop(columns=['status'], inplace = True)

In [118]:
col = ['id', 'title', 'tagline', 'release_date', 'genres', 'belongs_to_collection',
      'original_language', 'budget_musd', 'revenue_musd', 'production_companies', 
      'production_countries', 'vote_count', 'vote_average', 'popularity', 'runtime', 'overview',
      'spoken_languages', 'poster_path']

In [119]:
df = df.loc[:, col]

In [120]:
df.head(5)

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages,poster_path
0,862.0,Toy Story,NaN,1995-10-30,Animation|Comedy|Family,Toy Story Collection,en,30.0,373.554033,Pixar Animation Studios,United States of America,5415.0,7.7,21.946943,81.0,"Led by Woody, Andy's toys live happily in his ...",English,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1,8844.0,Jumanji,Roll the dice and unleash the excitement!,1995-12-15,Adventure|Fantasy|Family,NaN,en,65.0,262.797249,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,2413.0,6.9,17.015539,104.0,When siblings Judy and Peter discover an encha...,English|Français,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2,15602.0,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,1995-12-22,Romance|Comedy,Grumpy Old Men Collection,en,NaN,NaN,Warner Bros.|Lancaster Gate,United States of America,92.0,6.5,11.712900,101.0,A family wedding reignites the ancient feud be...,English,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3,31357.0,Waiting to Exhale,Friends are the people who let you be yourself...,1995-12-22,Comedy|Drama|Romance,NaN,en,16.0,81.452156,Twentieth Century Fox Film Corporation,United States of America,34.0,6.1,3.859495,127.0,"Cheated on, mistreated and stepped on, the wom...",English,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4,11862.0,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,1995-02-10,Comedy,Father of the Bride Collection,en,NaN,76.578911,Sandollar Productions|Touchstone Pictures,United States of America,173.0,5.7,8.387519,106.0,Just when George Banks has recovered from his ...,English,/e64sOI48hQXyru7naBFyssKFxVd.jpg

In [121]:
df.reset_index(drop = True, inplace = True)

In [122]:
base_poster_url = 'http://image.tmdb.org/t/p/w185/'
df.poster_path = "<img src='" + base_poster_url + df.poster_path + "' style='height:100px;'>"

In [123]:
df['poster_path'][0]

"<img src='http://image.tmdb.org/t/p/w185//rhIRbceoE9lR4veEXuwCC2wARtG.jpg' style='height:100px;'>"

In [124]:
df.to_csv('movies_cleaned1.csv', index= False)