In [1]:
# Working with Missing Data in Pandas
# Missing Data can occur when no information is provided for one or more
# items or for a whole unit. Missing Data is a very big problem in a real-life scenarios.
# Missing Data can also refer to as NA(Not Available) values in pandas.
# In DataFrame sometimes many datasets simply arrive with missing data,
# either because it exists and was not collected or it never existed.
# For Example, Suppose different users being surveyed may choose not to share their income,
# some users may choose not to share the address in this way many datasets went missing.

# Dataset : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

ufo = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [3]:
ufo.shape

(18241, 5)

In [4]:
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB

In [5]:
# check for missing values
ufo.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [6]:
# dropna()
# Remove missing values

ufo.dropna().shape

(2486, 5)

In [7]:
# handle missing data
# fillna()
# Fill NA/NaN values using the specified method.

ufo['City'].fillna(value='CityNotMentioned',inplace=True)

In [8]:
ufo['Colors Reported'].fillna(value='ColorNotKnown',inplace=True)

In [9]:
ufo['Shape Reported'].fillna(value='ShapeNotKnown',inplace=True)

In [10]:
ufo.isnull().sum()

City               0
Colors Reported    0
Shape Reported     0
State              0
Time               0
dtype: int64

In [11]:
# Load Another Dataset
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [12]:
data.isnull().sum()

Id            0
Name          0
Marks         2
Percentage    4
dtype: int64

In [13]:
# ffill
# forward fill
data['Marks'].fillna(method='ffill',inplace=True)

In [14]:
# bfill
# backward fill
data['Percentage'].fillna(method='bfill',inplace=True)

In [15]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        67.0
2   3  Alex   23.0        67.0
3   4  Alex   12.0        66.0
4   5  Alex   12.0        66.0
5   6  Alex   54.0        66.0
6   7  Alex   65.0        66.0

In [16]:
# fill missing data by taking up the mean value
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [17]:
mean_val = data['Percentage'].mean()
mean_val = round(mean_val,1)
data['Percentage'].fillna(value=mean_val,inplace=True)

In [18]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        70.3
2   3  Alex    NaN        67.0
3   4  Alex   12.0        70.3
4   5  Alex    NaN        70.3
5   6  Alex   54.0        70.3
6   7  Alex   65.0        66.0

In [19]:
# interpolate()
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [20]:
# interpolate()
'''
Python Pandas interpolate() method is used to fill NaN values in the DataFrame
or Series using various interpolation techniques to fill the missing values
rather than hard-coding the value.
Interpolation in Python is a technique used to estimate unknown data points
between two known data points.
'''

data.interpolate()

   Id  Name  Marks  Percentage
0   1  Alex   78.0       78.00
1   2  Alex   23.0       72.50
2   3  Alex   17.5       67.00
3   4  Alex   12.0       66.75
4   5  Alex   33.0       66.50
5   6  Alex   54.0       66.25
6   7  Alex   65.0       66.00

In [21]:
# Dealing with duplicate data
# Create a dataframe

data = {'StudentName':['John','Smith','Alex','Bob','John','Ali'],
       'Score':[45,65,76,44,45,39]}
df = pd.DataFrame(data)
df

  StudentName  Score
0        John     45
1       Smith     65
2        Alex     76
3         Bob     44
4        John     45
5         Ali     39

In [22]:
# check for duplicate records
# duplicated()

df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [23]:
df.duplicated().sum()

np.int64(1)

In [24]:
df[df.duplicated()]

  StudentName  Score
4        John     45

In [25]:
df[df['StudentName']=='John']

  StudentName  Score
0        John     45
4        John     45

In [26]:
# dropping duplicates
df.drop_duplicates(inplace=True)
df

  StudentName  Score
0        John     45
1       Smith     65
2        Alex     76
3         Bob     44
5         Ali     39

In [27]:
data = {'StudentName':['John','Smith','Alex','Bob','John','Ali'],
       'Score':[45,65,76,44,45,39]}
df = pd.DataFrame(data)
df

  StudentName  Score
0        John     45
1       Smith     65
2        Alex     76
3         Bob     44
4        John     45
5         Ali     39

In [28]:
df.duplicated(keep='last')

0     True
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [29]:
# dropping duplicates
df.drop_duplicates(inplace=True,keep='last')
df

  StudentName  Score
1       Smith     65
2        Alex     76
3         Bob     44
4        John     45
5         Ali     39