In [1]:
# Pandas
 
# pandas is a fast, powerful, flexible and easy to use open source data analysis and
# manipulation tool, built on top of the Python programming language.
 
# Pandas is the backbone of most data science projects.
 
'''
Pandas is an open-source Python library providing high-performance,
easy-to-use data structures and data analysis tools for the Python
programming language. Python with Pandas is used in a wide range of
fields including academic and commercial domains including finance,
economics, Statistics, analytics, etc.
 
In 2008, developer Wes McKinney started developing pandas when in need
of high performance, flexible tool for analysis of data.
 
Prior to Pandas, Python was majorly used for data munging and preparation.
It had very little contribution towards data analysis.
Pandas solved this problem. Using Pandas, we can accomplish five typical
steps in the processing and analysis of data, regardless of the
origin of data — load, prepare, manipulate, model, and analyze.
 
Key Features of Pandas
 
a.) Tools for loading data into in-memory data objects from different file formats.
 
b.) Data alignment and integrated handling of missing data.
 
c.) Label-based slicing, indexing and subsetting of large data sets.
 
d.) Columns from a data structure can be deleted or inserted.
 
e.) Group by data for aggregation and transformations.
 
f.) High performance merging and joining of data.
 
g.) Time Series functionality.
 
 
Numpy vs Pandas
 
a.) The Pandas module mainly works with the tabular data, whereas the NumPy module works with
the numerical data.
 
b.) The Pandas provides some sets of powerful tools like DataFrame and Series that mainly used
for analyzing the data, whereas in NumPy module offers a powerful object called Array.
 
c.) The Pandas covered the broader application because it is mentioned in 73 company stacks and
46 developer stacks, whereas in NumPy, 62 company stacks and 32 developer stacks are being
mentioned.
 
d.) Pandas has a better performance for 500K rows or more.  NumPy has a better performance for
50K rows or less.
 
'''
 
# Pandas
 
# a.) Series  --> is a 1D labelled data
 
# b.) DataFrame --> represent the data in tabular format

'\nPandas is an open-source Python library providing high-performance,\neasy-to-use data structures and data analysis tools for the Python\nprogramming language. Python with Pandas is used in a wide range of\nfields including academic and commercial domains including finance,\neconomics, Statistics, analytics, etc.\n \nIn 2008, developer Wes McKinney started developing pandas when in need\nof high performance, flexible tool for analysis of data.\n \nPrior to Pandas, Python was majorly used for data munging and preparation.\nIt had very little contribution towards data analysis.\nPandas solved this problem. Using Pandas, we can accomplish five typical\nsteps in the processing and analysis of data, regardless of the\norigin of data — load, prepare, manipulate, model, and analyze.\n \nKey Features of Pandas\n \na.) Tools for loading data into in-memory data objects from different file formats.\n \nb.) Data alignment and integrated handling of missing data.\n \nc.) Label-based slicing, indexing and subsetting of large data sets.\n \nd.) Columns from a data structure can be deleted or inserted.\n \ne.) Group by data for aggregation and transformations.\n \nf.) High performance merging and joining of data.\n \ng.) Time Series functionality.\n \n \nNumpy vs Pandas\n \na.) The Pandas module mainly works with the tabular data, whereas the NumPy module works with\nthe numerical data.\n \nb.) The Pandas provides some sets of powerful tools like DataFrame and Series that mainly used\nfor analyzing the data, whereas in NumPy module offers a powerful object called Array.\n \nc.) The Pandas covered the broader application because it is mentioned in 73 company stacks and\n46 developer stacks, whereas in NumPy, 62 company stacks and 32 developer stacks are being\nmentioned.\n \nd.) Pandas has a better performance for 500K rows or more.  NumPy has a better performance for\n50K rows or less.\n \n'

In [2]:
import numpy as np
import pandas as pd
print(pd.__version__)

2.2.3

In [3]:
arr = np.array([10,20,30,40])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]

In [4]:

s = pd.Series(arr)
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
dtype: int64

In [5]:
s = pd.Series([10,20,30],index=['val1','val2','val3'])
print(s)
print(s['val1'])
print(s.iloc[0])

val1    10
val2    20
val3    30
dtype: int64
10
10

In [6]:
s = pd.Series([10,20,30,40,50,60],index=['val1','val2','val3','val4','val5','val6'])
print(s)
print(s[0:4])
print()
print(s['val1':'val4'])

print('Using For Loop')
for i in s:
    print(i)

val1    10
val2    20
val3    30
val4    40
val5    50
val6    60
dtype: int64
val1    10
val2    20
val3    30
val4    40
dtype: int64

val1    10
val2    20
val3    30
val4    40
dtype: int64
Using For Loop
10
20
30
40
50
60

In [7]:
s = pd.Series([10,20,30,40,50,60],index=['val1','val2','val3','val4','val5','val6'])
print(s.get('val5'))
print(s.values)
print(s.shape)
print(s.index)
print(s.dtype)

# perform numerical computation
print('\nPerform numerical computation')
print(s*2)

50
[10 20 30 40 50 60]
(6,)
Index(['val1', 'val2', 'val3', 'val4', 'val5', 'val6'], dtype='object')
int64

Perform numerical computation
val1     20
val2     40
val3     60
val4     80
val5    100
val6    120
dtype: int64

In [8]:
# DataFrame
 
emp_info ={'Name':['John','Alex','Smith'],'Dept' :['IT','Sales','Finance'] , 'Salary':[35000,20000,40000]}
print(emp_info)

{'Name': ['John', 'Alex', 'Smith'], 'Dept': ['IT', 'Sales', 'Finance'], 'Salary': [35000, 20000, 40000]}

In [9]:
data = pd.DataFrame(emp_info)
print(type(data))
print(data)

<class 'pandas.core.frame.DataFrame'>
    Name     Dept  Salary
0   John       IT   35000
1   Alex    Sales   20000
2  Smith  Finance   40000

In [10]:

data

    Name     Dept  Salary
0   John       IT   35000
1   Alex    Sales   20000
2  Smith  Finance   40000

In [11]:
emp_info ={'Name':['John','Alex','Smith'],'Dept' :['IT','Sales','Finance'] , 'Salary':[35000,20000,40000]}
data = pd.DataFrame(emp_info,index=['Emp1','Emp2','Emp3'])
data

       Name     Dept  Salary
Emp1   John       IT   35000
Emp2   Alex    Sales   20000
Emp3  Smith  Finance   40000

In [12]:

data.shape

(3, 3)

In [13]:
data.columns

Index(['Name', 'Dept', 'Salary'], dtype='object')

In [14]:
print(data.Dept.values)

['IT' 'Sales' 'Finance']

In [15]:
data[['Dept','Salary']]

         Dept  Salary
Emp1       IT   35000
Emp2    Sales   20000
Emp3  Finance   40000

In [16]:
# locate row
data.loc['Emp1']

Name       John
Dept         IT
Salary    35000
Name: Emp1, dtype: object

In [17]:
data.loc[['Emp2','Emp3']]

       Name     Dept  Salary
Emp2   Alex    Sales   20000
Emp3  Smith  Finance   40000

In [18]:
# date_range('yyyymmdd',periods=10)
dates = pd.date_range('20250201',periods=10)
dates

DatetimeIndex(['2025-02-01', '2025-02-02', '2025-02-03', '2025-02-04',
               '2025-02-05', '2025-02-06', '2025-02-07', '2025-02-08',
               '2025-02-09', '2025-02-10'],
              dtype='datetime64[ns]', freq='D')

In [19]:
df = pd.DataFrame(np.random.rand(10,4),index=dates,columns=list('ABCD'))
df

                   A         B         C         D
2025-02-01  0.865006  0.808965  0.001216  0.716274
2025-02-02  0.722770  0.934642  0.870664  0.675884
2025-02-03  0.106172  0.335908  0.732534  0.400317
2025-02-04  0.456929  0.686838  0.751632  0.793721
2025-02-05  0.413094  0.467703  0.516400  0.418102
2025-02-06  0.233385  0.422730  0.385288  0.973545
2025-02-07  0.801690  0.800708  0.446213  0.985708
2025-02-08  0.873199  0.123429  0.546691  0.331513
2025-02-09  0.304925  0.906475  0.558983  0.821367
2025-02-10  0.636972  0.862071  0.186901  0.700577

In [20]:
emp_info = {'Id':[101,102,103,104,105,106] , 'Name':['John','Smith','Nurul','Tom','Harry','Smith']
            , 'Salary':[1000,2000,3000,1200,2800,3200]
            ,'Dept':['Finance','Sales','HR','IT','Marketing','Sales']}
data = pd.DataFrame(emp_info)
data

    Id   Name  Salary       Dept
0  101   John    1000    Finance
1  102  Smith    2000      Sales
2  103  Nurul    3000         HR
3  104    Tom    1200         IT
4  105  Harry    2800  Marketing
5  106  Smith    3200      Sales

In [21]:
data[data['Salary'] > 1500]

    Id   Name  Salary       Dept
1  102  Smith    2000      Sales
2  103  Nurul    3000         HR
4  105  Harry    2800  Marketing
5  106  Smith    3200      Sales

In [22]:
data[(data['Salary'] > 1500) & (data['Dept']=='Sales')]

    Id   Name  Salary   Dept
1  102  Smith    2000  Sales
5  106  Smith    3200  Sales

In [23]:
# Pandas
# Pandas is a powerful and flexible Python package that allows you to work with labeled and
# time series data. It also provides statistics methods, enables plotting, and more.
# One crucial feature of pandas is its ability to write and read Excel, CSV, and many other types of files.
 
# Reading An Excel File
# Reading A CSV File
# Reading tab-delimited file
# Reading A JSON File
# Uploading Local Files In Jupyter / Google Colab

In [24]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\tanis\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\tanis\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

In [25]:
# Reading An Excel File
# read_excel()

data = pd.read_excel('https://raw.github.com/yash240990/Python/master/sampleExcelData.xlsx')
data

,id,first_name,last_name,email,gender,ip_address
0,1,Merle,Draisey,mdraisey0@squarespace.com,Bigender,20.70.199.51
1,2,Casey,Sheach,csheach1@deviantart.com,Male,226.126.229.167
2,3,Darya,Leivers,dleivers2@imgur.com,Female,247.209.88.235
3,4,Fancie,Casebourne,fcasebourne3@g.co,Female,172.34.162.239
4,5,Jenilee,Vsanelli,jvsanelli4@fc2.com,Female,200.104.246.2
...,...,...,...,...,...,...
995,996,Lutero,Yurov,lyurovrn@un.org,Male,95.146.16.187
996,997,Verla,Peery,vpeeryro@com.com,Female,172.90.253.234
997,998,Fran,Langran,flangranrp@ft.com,Male,123.179.99.154
998,999,Gabbi,Cummins,gcumminsrq@jugem.jp,Female,190.13.174.159
999,1000,Gloriane,Marc,gmarcrr@businessweek.com,Female,139.87.192.32

In [26]:
excelFile = pd.ExcelFile('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelFile.sheet_names

['data', 'Sheet2']

In [27]:
data = pd.read_excel(excelFile,'Sheet2')
data

   first_name    last_name                                 email
0       Merle      Draisey             mdraisey0@squarespace.com
1       Casey       Sheach               csheach1@deviantart.com
2       Darya      Leivers                   dleivers2@imgur.com
3      Fancie   Casebourne                     fcasebourne3@g.co
4     Jenilee     Vsanelli                    jvsanelli4@fc2.com
5    Charmian    Drinkhall       cdrinkhall5@theglobeandmail.com
6     Janessa       Kivell                 jkivell6@linkedin.com
7       Mirna       Heinsh                  mheinsh7@spotify.com
8       Darby          Lax                   dlax8@people.com.cn
9       Meryl        Riehm                 mriehm9@princeton.edu
10       Anne        Brody                    abrodya@sphinn.com
11       Puff    Langsbury             plangsburyb@canalblog.com
12       Tina      Gregoli                  tgregolic@sfgate.com
13     Barbie       Dahlen                     bdahlend@narod.ru
14     Andeee  Dobrovolski  adobrovolskie@networkadvertising.org
15    Ainsley       Friman                      afrimanf@irs.gov
16        Bil     Shalcros                 bshalcrosg@dion.ne.jp
17    Raimund     Outridge                   routridgeh@lulu.com
18     Whitby     Millward                    wmillwardi@ask.com
19        Rob      Boarder                       rboarderj@51.la
20      Nicky     Curthoys                    ncurthoysk@pbs.org

In [28]:
# read a CSV file
data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv')
data

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [29]:
# read a TXT format file
data = pd.read_csv('https://www.inf.ed.ac.uk/teaching/courses/inf2b/labs/iris.txt',sep='\t')
data

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

In [30]:
# read json
data = pd.read_json('https://raw.githubusercontent.com/yash240990/Python/master/simple.json')
data

     id   name  math  physics  chemistry
0  A001    Tom    60       66         61
1  A002  James    89       76         51
2  A003  Jenny    79       90         78